highlighter: rouge

permalink: :year/:month/:day/:title 

baseurl: /ComicsCalendar

title : ComicsCalendar
author :
  name : RÃ©my Gardette
  website: http://remyg.fr
  email : remy.gardette@gmail.com
  github : RemyG
  twitter : remygardette
  feedburner : feedname
